name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: SurajsMishra
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=orange,#FF8C00,#FF8C00&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39&color_dot_border=#d0d7de
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
